added new operators Write, Add, Branch, and BranchNeg
alan-whitman/CS2450GroupProject pull request #14
Opened 2021-07-30 22:37 UTC by ramenNoodles1998

2021-07-30 23:19 UTC, alan-whitman requested changes
Both of the branch commands here will not function. You're returning values, but if you look at basicml.py, those return values aren't being capture by anything due to the architecture change, so they're just going off into the aether. Instead, just manipulate the instruction counter directly. E.g. for Branch:

bml.instruction_counter = bml.operand

In the case of BranchNeg, previously we were passing both the operand and the existing instruction_counter because we had to return the instruction_counter instead of the operand if the condition wasn't met. With the new architecture, if the condition isn't met, you don't have to do anything.

Write and Add both look good.

2021-07-31 19:52 UTC, ramenNoodles1998 commented
I added the new changes

2021-08-01 15:18 UTC, alan-whitman requested changes
All the operators look great now!

There are a couple issues with validate_instruction. First, on line 29, you need to change the second part of the conditional logic. All numbers are < 10000 or > 4299, so everything except 43 will be invalid under the current logic. Basically, the 4299 needs to be 42999 (the largest possible valid instruction).

Second, on line 31, you need to floor divide by 1000 instead of 100. Floor dividing by a power of 10 like this will essentially chop off the last n digits of the number, where n is the power of ten. Previously when we had 4 digit instructions, to get the opcode we were chopping off 2 digits, and so dividing by 10^2. Since we now have 5 digit instructions, we need to divide by 10^3, i.e. 1000, instead.

2021-08-01 18:48 UTC, alan-whitman approved these changes

2021-08-01 18:48 UTC, merged